### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by KnorpelSenf** [grammyjs/menu#7]
There are two issues and a number of tiny improvements that should land for the 1.0 release.

- #3
- #6
- ~~outdated menu handler should have navigation control access, and the default handler should leverage that~~ awful types and worse performance
- [x] `DynamicString` should only be a function, and the current version should be called `MaybeDynamicString`
- [x] Make `addRange` public
- [x] Make `add` public and let it accept many buttons
- [x] Fix `Range` class not appearing in API reference (expose directly and rename to `MenuRange`, not on `Menu` instance)
- [x] Document default values of config options
- [x] Write plugin docs on https://grammy.dev
- [x] Drop the byte count because fingerprints and payloads add to much uncertainty for the check to be meaningful

If user testing reveals further flaws in the design of this plugin, the above list will be extended.

If you want to work on any of the things, please leave a comment here so no work is done twice.

**Comment by KnorpelSenf** [comment]
Please test this plugin, and give feedback! It should be ready to use. No further changes are planned, unless you bring up something.

**Comment by KnorpelSenf** [comment]
1.0 released in a0cd64a02681ef33d2a2a5517f85818dfe83f1d7
